### ISSUE TITLE
Align with rfc8348

### ISSUE THREAD

**Issue by boucadair** [ietf-ivy-wg/network-inventory-yang#57]
https://github.com/ietf-ivy-wg/network-inventory-yang/blob/d13257a88ddef39df709dd6dd803c9a9c3361302/ietf-network-inventory.yang#L285

Can this be aligned with rfc8348 naming?

**Comment by italobusi** [comment]
@boucadair : it was a conscious design decision not to align with RFC8348 due to some limitations of using names as keys for YANG lists

We have discovered that there are use cases where the name of a managed object is changed by the operator and sometimes the names assigned by the operators are not unique. Therefore this type of name cannot be used as a key of a YANG list

There are also some cases where it is very hard to guarantee uniqueness of the names (e.g., when there are multiple controllers creating entries in the list): https://github.com/tsaad-dev/te/issues/50)

To avoid these issues the keys of the list can better be URIs or UUIDs

To give more implementation freedom we have agreed to define the key as a string which may or not match with the name, the UUID,  or the URI:

https://github.com/ietf-ivy-wg/network-inventory-yang/blob/main/minutes/minutes-2024-01-17.md

We have proposed to add some clarification text to the I-D: see PR #65 

Co-Authored-By: YuChaode <25008042+YuChaode@users.noreply.github.com>

**Comment by italobusi** [comment]
**[2024-10-02 Base Network Inventory weekly call](https://github.com/ietf-ivy-wg/network-inventory-yang/wiki/minutes-2024-10-02)**

Agreed to keep the current design decision: https://github.com/ietf-ivy-wg/network-inventory-yang/issues/57#issuecomment-2383150027
